# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'PayIt' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  inherit! :search_paths
  # Pods for PayIt
  pod 'Firebase/Core'

  pod 'react-native-config', :path => '../node_modules/react-native-config'

  target 'PayItTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
