# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'PayIt' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  inherit! :search_paths
  # Pods for PayIt
  pod 'GoogleSignIn'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Firebase/Auth'

  pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
	'Core',
	'DevSupport',
	'RCTNetwork',
    # Add any other subspecs you want to use in your project
  ]

  pod 'react-native-config', :path => '../node_modules/react-native-config'

  target 'PayItTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
	installer.pods_project.targets.each do |target|
	  if target.name == 'react-native-config'
		phase = target.project.new(Xcodeproj::Project::Object::PBXShellScriptBuildPhase)
		phase.shell_script = "cd ../../"\
							 " && RNC_ROOT=./node_modules/react-native-config/"\
							 " && export SYMROOT=$RNC_ROOT/ios/ReactNativeConfig"\
							 " && export BUILD_DIR=$RNC_ROOT/ios/ReactNativeConfig"\
							 " && ruby $RNC_ROOT/ios/ReactNativeConfig/BuildDotenvConfig.ruby"
  
		target.build_phases << phase
		target.build_phases.move(phase,0)
	  end
	end
  end
